version: '3.8'

services:
  api_db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    container_name: api_db
    ports:
      - "5433:5432"

  api:
    build: .
    restart: always
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:  # Changed 'volume' to 'volumes'
      - .:/app
    env_file: .env
    depends_on:
      - api_db
